In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv('data/train.csv', index_col='Id')
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
Id,,,,,,,,,,,
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0

In [13]:
columns = df.columns
columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='str')

In [14]:
df.isnull().sum()

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           20781
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       2749
dtype: int64

In [28]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
SeriousDlqin2yrs,104805.0,0.066314,0.248831,0.0,0.000000,0.000000,0.000000,1.0
RevolvingUtilizationOfUnsecuredLines,104805.0,5.602014,217.389876,0.0,0.029801,0.153984,0.559168,29110.0
age,104805.0,52.351128,14.765944,0.0,41.000000,52.000000,63.000000,109.0
NumberOfTime30-59DaysPastDueNotWorse,104805.0,0.416077,4.139291,0.0,0.000000,0.000000,0.000000,98.0
DebtRatio,104805.0,354.859470,2169.182855,0.0,0.175026,0.366626,0.867267,329664.0
MonthlyIncome,84024.0,6684.452859,15653.133457,0.0,3400.000000,5400.000000,8250.000000,3008750.0
NumberOfOpenCreditLinesAndLoans,104805.0,8.454854,5.127986,0.0,5.000000,8.000000,11.000000,58.0
NumberOfTimes90DaysLate,104805.0,0.259988,4.115594,0.0,0.000000,0.000000,0.000000,98.0
NumberRealEstateLoansOrLines,104805.0,1.019551,1.136847,0.0,0.000000,1.000000,2.000000,54.0
NumberOfTime60-89DaysPastDueNotWorse,104805.0,0.235571,4.101263,0.0,0.000000,0.000000,0.000000,98.0
NumberOfDependents,102056.0,0.756065,1.112162,0.0,0.000000,0.000000,1.000000,13.0

In [21]:
df.shape

(104805, 11)

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 104805 entries, 1 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      104805 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  104805 non-null  float64
 2   age                                   104805 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  104805 non-null  int64
 4   DebtRatio                             104805 non-null  float64
 5   MonthlyIncome                         84024 non-null   float64
 6   NumberOfOpenCreditLinesAndLoans       104805 non-null  int64
 7   NumberOfTimes90DaysLate               104805 non-null  int64
 8   NumberRealEstateLoansOrLines          104805 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  104805 non-null  int64
 10  NumberOfDependents                    102056 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 9.6 MB

In [23]:
df.duplicated().sum()

np.int64(353)

In [26]:
df.dtypes

SeriousDlqin2yrs                          int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

In [27]:
df.nunique()

SeriousDlqin2yrs                            2
RevolvingUtilizationOfUnsecuredLines    88520
age                                        85
NumberOfTime30-59DaysPastDueNotWorse       15
DebtRatio                               82227
MonthlyIncome                           12147
NumberOfOpenCreditLinesAndLoans            58
NumberOfTimes90DaysLate                    19
NumberRealEstateLoansOrLines               26
NumberOfTime60-89DaysPastDueNotWorse       12
NumberOfDependents                         12
dtype: int64

In [29]:
df['age'].value_counts().sort_index()

age
0        1
21     132
22     301
23     451
24     564
      ...
101      2
102      3
103      3
105      1
109      1
Name: count, Length: 85, dtype: int64

In [31]:
(df['NumberOfTime30-59DaysPastDueNotWorse'] == 98).sum()

np.int64(181)

In [32]:
(df['NumberOfTime60-89DaysPastDueNotWorse'] == 98).sum()

np.int64(181)

In [33]:
(df['NumberOfTimes90DaysLate'] == 98).sum()

np.int64(181)

In [37]:
mask_98 = (
    (df['NumberOfTime30-59DaysPastDueNotWorse'] == 98) &
    (df['NumberOfTime60-89DaysPastDueNotWorse'] == 98) &
    (df['NumberOfTimes90DaysLate'] == 98)
)

mask_98.sum()

np.int64(181)

In [38]:
(df['age'] < 18).sum()

np.int64(1)

In [39]:
(df['age'] > 100).sum()

np.int64(10)

In [42]:
print(df.loc[mask_98, 'SeriousDlqin2yrs'].value_counts())
print(df.loc[mask_98, 'SeriousDlqin2yrs'].mean())
print(df.loc[~mask_98, 'SeriousDlqin2yrs'].mean())

SeriousDlqin2yrs
1    95
0    86
Name: count, dtype: int64
0.5248618784530387
0.06552033950145282